"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { track } from "@vercel/analytics";
import { Faq, Footer, Nav } from "@/components/chrome";
import { Card, ResultScreen, TreeScreen } from "@/components/screens";
import { ApiError, getRules } from "@/lib/api";
import { generateWithFallback } from "@/lib/offline";
import { resetSession, session } from "@/lib/session";

export default function ConvertPage() {
  const router = useRouter();
  const [ready, setReady] = useState(false);
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const [target, setTarget] = useState<"kaggle" | "colab">(session.target);
  const [notebookName, setNotebookName] = useState(session.notebookName);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [resultUrl, setResultUrl] = useState<string | null>(null);
  const maxBytesRef = useRef(4 * 1024 * 1024);

  useEffect(() => {
    if (session.files.length === 0 || !session.scan) {
      router.replace("/");
      return;
    }
    getRules()
      .then((r) => {
        maxBytesRef.current = r.limits.max_total_bytes;
        setChecked(
          new Set(
            session.scan!.files
              .filter((f) => f.included && f.size <= r.limits.large_file_bytes)
              .map((f) => f.path),
          ),
        );
        setReady(true);
      })
      .catch(() => setError("Can't reach the conversion API. Is it running on port 8000?"));
  }, [router]);

  const scan = session.scan;
  const entries = session.entries;

  const checkedNodes = useMemo(
    () => (scan ? scan.files.filter((f) => checked.has(f.path)) : []),
    [scan, checked],
  );
  const budget = checkedNodes.reduce((s, f) => s + f.size, 0);

  /** Session overrides as a portable .repo2nbignore */
  const ignoreFile = useMemo(() => {
    if (!scan) return "";
    const lines: string[] = ["# generated by repo2nb: session overrides", "#"];
    for (const f of scan.files) {
      if (f.included && !checked.has(f.path)) lines.push(f.path);
      else if (!f.included && checked.has(f.path)) lines.push(`!${f.path}`);
    }
    return lines.length > 2 ? lines.join("\n") + "\n" : "";
  }, [scan, checked]);

  const notebookFile = `${(notebookName.trim() || "project").replace(/\.ipynb$/i, "").replace(/\s+/g, "-")}-${target}.ipynb`;

  async function onGenerate() {
    if (!scan || checked.size === 0 || budget > maxBytesRef.current) return;
    setBusy(true);
    setError(null);
    try {
      const blob = await generateWithFallback(entries, [...checked], target);
      track("notebook_generated");
      setResultUrl((prev) => {
        if (prev) URL.revokeObjectURL(prev);
        return URL.createObjectURL(blob);
      });
    } catch (e) {
      setError(e instanceof ApiError ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  function onReset() {
    resetSession();
    router.push("/");
  }

  return (
    <>
      <Nav />
      <main className="mx-auto max-w-3xl px-5 pt-10 pb-16">
        {error && (
          <p role="alert" className="mb-4 rounded-md border border-warn/40 bg-warn/10 px-3 py-2 text-sm text-warn font-mono">
            {error}
          </p>
        )}
        {ready && scan ? (
          resultUrl ? (
            <Card>
              <ResultScreen
                url={resultUrl}
                filename={notebookFile}
                ignoreText={ignoreFile}
                onReset={onReset}
              />
            </Card>
          ) : (
            <Card>
              <TreeScreen
                scan={scan}
                checked={checked}
                setChecked={setChecked}
                budget={budget}
                maxBytes={maxBytesRef.current}
                target={target}
                setTarget={(t) => {
                  session.target = t;
                  setTarget(t);
                }}
                notebookName={notebookName}
                setNotebookName={(n) => {
                  session.notebookName = n;
                  setNotebookName(n);
                }}
                onGenerate={onGenerate}
                busy={busy}
                onReset={onReset}
              />
            </Card>
          )
        ) : (
          !error && <p className="text-center font-mono text-sm text-muted">loading…</p>
        )}
      </main>
      <Faq />
      <Footer />
    </>
  );
}
